"""Generate the frontend's shared types and OpenAPI snapshot from Python contracts.

Run from any directory: python scripts/export_contracts.py [--check]
No model calls, database access or Node dependencies are needed.
"""

# ruff: noqa: E402

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "services/api"))

from app.main import app
from app.models import contracts, responses
from pydantic import BaseModel


def ts(schema):
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(x) for x in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(ts(x) for x in schema["anyOf"])
    kind = schema.get("type")
    if kind == "array":
        return f"Array<{ts(schema['items'])}>"
    if kind == "object":
        if schema.get("properties") == {}:
            return "Record<string, never>"
        if "properties" in schema:
            return "{ " + "; ".join(f"{json.dumps(k)}: {ts(v)}" for k, v in schema["properties"].items()) + " }"
        value = schema.get("additionalProperties", {})
        return f"Record<string, {ts(value) if isinstance(value, dict) else 'unknown'}>"
    return {"string": "string", "integer": "number", "number": "number", "boolean": "boolean", "null": "null"}.get(
        kind, "unknown"
    )


def artifacts():
    definitions = {}
    for module in (contracts, responses):
        for name, model in vars(module).items():
            if isinstance(model, type) and issubclass(model, BaseModel) and model.__module__ == module.__name__:
                schema = model.model_json_schema(mode="serialization")
                definitions.update(schema.pop("$defs", {}))
                definitions[name] = schema
    lines = ["// Generated by scripts/export_contracts.py. Do not edit by hand.", "// API contract version 1.1.", ""]
    for name, schema in sorted(definitions.items()):
        lines.append(f"export type {name} = {ts(schema)};")
    return {
        ROOT / "apps/web/lib/contracts.generated.ts": "\n".join(lines) + "\n",
        ROOT / "docs/api/openapi.json": json.dumps(app.openapi(), indent=2, sort_keys=True) + "\n",
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, content in artifacts().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if stale:
        raise SystemExit("Regenerate API contracts: " + ", ".join(stale))


if __name__ == "__main__":
    main()
